### ISSUE TITLE
Android: Native Video Player does not work

### ISSUE THREAD

**Issue by awatertrevi** [brminnick/AzureMediaServicesSampleApp#6]
When watching the Encrypted Video Source on a physical Android Device the video won't load.

After specifying the MediaType as suggested here: https://github.com/martijn00/XamarinMediaManager/issues/450 you run into the problem that HLS doesn't support bearer tokens in the header.

This is something you can work around by using a HLS proxy as described here: http://mingfeiy.azurewebsites.net.

However; I am still left with the following stacktrace after successfully obtaining the manifest:

```
[ExoPlayerImplInternal] Source error.
[ExoPlayerImplInternal] com.google.android.exoplayer2.source.hls.SampleQueueMappingException: Unable to bind a sample queue to TrackGroup with mime type audio/mp4a-latm.
[ExoPlayerImplInternal] 	at com.google.android.exoplayer2.source.hls.HlsSampleStream.maybeThrowError(HlsSampleStream.java:64)
[ExoPlayerImplInternal] 	at com.google.android.exoplayer2.BaseRenderer.maybeThrowStreamError(BaseRenderer.java:129)
[ExoPlayerImplInternal] 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:538)
[ExoPlayerImplInternal] 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
[ExoPlayerImplInternal] 	at android.os.Handler.dispatchMessage(Handler.java:98)
[ExoPlayerImplInternal] 	at android.os.Looper.loop(Looper.java:154)
[ExoPlayerImplInternal] 	at android.os.HandlerThread.run(HandlerThread.java:61)
```

```
public const string EncryptedVideoUrl = @"http://mingfeiy.azurewebsites.net/Home/Manifest?playbackUrl=http%3a%2f%2famssamples.streaming.mediaservices.windows.net%2f830584f8-f0c8-4e41-968b-6538b9380aa5%2fTearsOfSteelTeaser.ism%2fmanifest(format%3dm3u8-aapl)&webtoken=Bearer%3deyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1cm46bWljcm9zb2Z0OmF6dXJlOm1lZGlhc2VydmljZXM6Y29udGVudGtleWlkZW50aWZpZXIiOiI5ZGRhMGJjYy01NmZiLTQxNDMtOWQzMi0zYWI5Y2M2ZWE4MGIiLCJpc3MiOiJodHRwOi8vdGVzdGFjcy5jb20vIiwiYXVkIjoidXJuOnRlc3QiLCJleHAiOjE3MTA4MDczODl9.lJXm5hmkp5ArRIAHqVJGefW2bcTzd91iZphoKDwa6w8";
 ```

**Comment by awatertrevi** [comment]
I managed to fix it using just the ExoPlayer instead of the MediaManager plugin. Here is how: https://www.pshul.com/2018/02/09/xamarin-forms-android-using-exoplayer-in-your-app/
